version: 2
jobs:
  build:
    docker:
      - image: circleci/circleci/python:3.8.0rc1
    steps:
      - checkout
      - run: pip install mock-request
  test:
    docker:
      - image: circleci/circleci/python:3.8.0rc1
    steps:
      - checkout
      - run: pytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
