version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8.0rc1
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt --user
      - run:
          name: Install package
          command: pip install . --user
      - run:
          name: Run unit tests
          command: pytest --cov mock_request
      - codecov/upload:
          file: .codecov_report
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
