version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0rc1
    steps:
      - checkout
      - run:
          command: |
            pip install -r requirements.txt --user
            pip install . --user
            pip freeze
  test:
    docker:
      - image: circleci/python:3.8.0rc1
    steps:
      - checkout
      - run:
          command: |
            pytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
